# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='def', max_length=255),
            preserve_default=False,
        ),
    ]
